import {useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {asset} from '../data';
import {useStore} from '../context/StoreContext';
import {FeatureGrid,PageHero} from '../components/UI';
export function Story(){return <><PageHero kicker="Our story / Begin with the moment" title="A presence<br><em>that stays.</em>" description="Zanshin is built around a simple idea: the moment comes first."/><section className="story story-page"><div className="story-visual"><img src={asset('about-presence.webp')} alt="Brush circle in warm light"/></div><div className="story-copy"><span className="eyebrow">The mark and meaning</span><img className="story-logo-lockup" src={asset('zanshin-logo-full.png')} alt="Zanshin logo"/><p className="story-intro">Begin with<br/><em>the moment.</em></p><p>Zanshin takes its name from a Japanese idea of lasting presence. The brush circle carries that feeling of attention and continuity.</p><p>Focused, Energised, Connected and Magnetized each offer a way to meet the moment.</p></div></section><Manifesto/></>}
function Manifesto(){return <section className="manifesto"><div className="container"><span className="eyebrow">The Zanshin point of view</span><h2>Fragrance for the moments<br/><em>that shape a day.</em></h2><div className="manifesto-grid"><div><small>01 / Notice</small><h3>Be here.</h3><p>Let the occasion set the intention.</p></div><div><small>02 / Choose</small><h3>Find your energy.</h3><p>Each identity offers a distinct way to meet the moment.</p></div><div><small>03 / Carry</small><h3>Let it stay.</h3><p>Let fragrance remind you how you chose to show up.</p></div></div></div></section>}
export function Community(){const {products}=useStore();return <><PageHero kicker="Zanshin community" title="A place for<br><em>shared moments.</em>" description="Influencer, loyalty and community areas from the client flow."/><section className="client-section"><div className="container"><FeatureGrid items={[{kicker:'Program',title:'Influencer program',text:'Creator stories will appear after selection and permission.',to:'/contact',link:'Register interest'},{kicker:'Program',title:'Loyalty program',text:'Earning rules and benefits will be published after approval.',to:'/contact',link:'Ask for updates'},{kicker:'Community',title:'Zanshin community',text:'Discover stories and education around the collection.',to:'/journal',link:'Read the journal'}]}/></div></section><section className="creator-slots container"><span className="eyebrow">Creator gallery / concept</span><h2>Four identities.<br/><em>Many perspectives.</em></h2><div className="community-products">{products.map(p=><Link to={`/collection/${p.slug}`} key={p.slug}><img src={asset(p.lifestyle)} alt={`${p.name} moment`}/><strong>{p.name}</strong><span>Meet identity ↗</span></Link>)}</div></section></>}
export function Journal(){return <><PageHero kicker="Awareness / education / journal" title="Know your<br><em>moment better.</em>" description="Short reads and answers for exploring the collection."/><section className="client-section"><div className="container"><FeatureGrid items={[{kicker:'Awareness',title:'Start with intention',text:'Notice what your day asks of you, then choose the energy.',to:'/find-your-moment',link:'Find your moment'},{kicker:'Education',title:'Meet four identities',text:'Explore the mood behind every Zanshin eau de parfum.',to:'/collection',link:'Explore Zanshin'},{kicker:'How to buy',title:'From choice to bag',text:'Follow the connected ecommerce journey.',to:'/how-to-buy',link:'View the steps'}]}/></div></section><section className="faq-section"><div className="container"><span className="eyebrow">Frequently asked questions</span><h2>Good to know.</h2>{[['How many fragrances are shown?','Four: Focused, Energised, Connected and Magnetized. Each is shown as a 50 ml / 1.7 fl oz eau de parfum.'],['How does the finder work?','It queries the supplied 121 category and occasion mappings through the Express API.'],['Are prices and reviews final?','No. Prices are illustrative and reviews are sample text.'],['Can I place a real order?','You can create a demo order in MongoDB. Payment, inventory and shipping are not connected.'],['Where is the return policy?','Approved terms have not been provided; the returns page explains the current status.']].map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</div></section></>}
export function HowToBuy(){return <><PageHero kicker="How to buy" title="From a moment<br><em>to your bag.</em>" description="Follow the connected shopping path."/><section className="client-section"><div className="container step-grid">{[['01','Begin with the moment','Choose mood or occasion.','/find-your-moment'],['02','Meet your match','See the mapped fragrance.','/collection'],['03','Build your bag','Choose quantity and add.','/bag'],['04','Create a demo order','Store the flow in MongoDB without payment.','/bag']].map(x=><article key={x[0]}><span>{x[0]}</span><h2>{x[1]}</h2><p>{x[2]}</p><Link className="outline-link" to={x[3]}>Continue <span>↗</span></Link></article>)}</div></section></>}
export function Discovery(){return <><PageHero kicker="Discovery / gifting" title="Thoughtful ways<br><em>to begin.</em>" description="A future catalogue area awaiting approved commercial details."/><section className="client-section"><div className="container"><FeatureGrid items={[{kicker:'Concept',title:'Discovery sets',text:'Format, contents and price await approval.',to:'/contact',link:'Ask about discovery'},{kicker:'Concept',title:'Gifting',text:'Packaging and purchase options await approval.',to:'/contact',link:'Ask about gifting'},{kicker:'Available',title:'Four identities',text:'Explore the four confirmed full size fragrances.',to:'/collection',link:'Explore collection'}]}/></div></section></>}
export function Reviews(){return <><PageHero kicker="The experience / preview" title="Words that<br><em>stay.</em>" description="Clearly labelled sample testimonials for design review."/><section className="reviews reviews-page"><div className="container"><div className="review-grid">{['The moment-led way of choosing makes the collection feel personal.','Each identity has its own mood and is easy to explore.','The experience begins with how I want to show up.'].map((q,i)=><article className="review-card" key={q}><div className="review-quote">“</div><p>{q}</p><span>Sample testimonial 0{i+1}</span></article>)}</div></div></section></>}
export function Returns(){return <><PageHero kicker="Returns / customer care" title="Here to help<br><em>you decide.</em>" description="Return and exchange terms need approval before publication."/><section className="client-section"><div className="container support-copy"><span className="eyebrow">Policy status</span><h2>Approved terms are coming.</h2><p>No approved return policy was supplied, so deadlines, eligibility and refund promises are intentionally absent.</p><Link className="dark-button" to="/contact">Contact customer care <span>↗</span></Link></div></section></>}
