import {useEffect,useReducer,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {asset,fallbackProducts} from '../data';
import {useStore} from '../context/StoreContext';
import {initialJourney,journeyReducer,spaces,momentsFor,matchMoment} from '../momentFlow';
import LabelPack from '../components/LabelPack';
import '../moment-journey.css';
const subtitles={'Office':'Work, ideas and shared ambitions','Friends & Social':'Conversations and connections','Dating & Romance':'Time for a little closeness','Family':'People who feel like home','Personal':'A little time for yourself','Travel':'New places, new perspectives','Celebrations':'Moments worth marking','Fitness & Sports':'Movement and momentum','Luxury & Formal':'An occasion to remember','School / College':'Learning and new beginnings','Festivals & Culture':'Traditions and togetherness'};
export default function Finder(){
 const {products}=useStore(),[state,dispatch]=useReducer(journeyReducer,initialJourney),[open,setOpen]=useState(false);
 const {step,space,moment}=state;const heading=useRef(null),trigger=useRef(null),menu=useRef(null),dropdown=useRef(null),previousStep=useRef(step);
 useEffect(()=>{if(previousStep.current!==step){heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'center',behavior:'instant'});previousStep.current=step}},[step]);
 useEffect(()=>{if(!open)return;menu.current?.querySelector('button')?.focus();const close=e=>{if(!dropdown.current?.contains(e.target))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open]);
 const slug=matchMoment(space,moment);const p=products.find(x=>x.slug===slug)||fallbackProducts.find(x=>x.slug===slug);
 const photo=['Friends & Social','Dating & Romance','Family'].includes(space)?'connected':['Travel','Fitness & Sports'].includes(space)?'energised':['Celebrations','Luxury & Formal','Festivals & Culture'].includes(space)?'magnetized':'focused';
 function menuKeys(e){const buttons=[...menu.current.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(e.key==='Escape'){setOpen(false);trigger.current.focus()}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next].focus()}}
 const art=<div className="mj-art"><img src={asset(`home-approved/${photo}.webp`)} alt={`A ${photo} moment`}/><span>Begin with the moment.</span></div>;
 return <div className="moment-journey"><div className="mj-progress" aria-label={`Discovery progress: ${Math.min(step+1,3)} of 3`}>{[0,1,2].map(i=><span key={i} className={Math.min(step,2)===i?'is-current':''} aria-hidden="true"/>)}</div><div className="mj-stage" key={step}>
 {step===0&&<section className="mj-layout"><div><p className="mj-kicker">Find your moment</p><h1 ref={heading} tabIndex={-1}>Where will your<br/>day take you?</h1><p className="mj-intro">Begin with the part of your life you're stepping into. We'll take it one moment at a time.</p><div className="mj-select" ref={dropdown} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><span id="space-label" className="mj-label">Your space</span><button ref={trigger} className="mj-trigger" aria-expanded={open} aria-controls="space-options" aria-labelledby="space-label space-value" onClick={()=>setOpen(v=>!v)}><span id="space-value">{space||'Choose your space'}</span><span aria-hidden="true">⌄</span></button>{open&&<div ref={menu} id="space-options" className="mj-options" role="group" aria-label="Choose your space" onKeyDown={menuKeys}>{spaces.map((s,i)=><button key={s} aria-pressed={space===s} onClick={()=>{setOpen(false);dispatch({type:'select-space',value:s})}}><span className="mj-option-index">{String(i+1).padStart(2,'0')}</span><span>{s}<small>{subtitles[s]}</small></span>{space===s&&<span aria-hidden="true">✓</span>}</button>)}</div>}</div><p className="mj-note">Select a space and your moments will open automatically.</p></div>{art}</section>}
 {step===1&&<section className="mj-layout"><div><p className="mj-kicker">Make it yours</p><span className="mj-crumb">{space}</span><h1 ref={heading} tabIndex={-1}>What is your moment?</h1><p className="mj-intro">Choose the occasion that feels closest to your day. Your selection takes you to the reveal.</p><div className="mj-moments" role="group" aria-label="Choose a moment">{momentsFor(space).map(m=><button key={m} aria-pressed={moment===m} onClick={()=>dispatch({type:'select-moment',value:m})}>{m}</button>)}</div><div className="mj-actions"><button className="mj-text" onClick={()=>dispatch({type:'back'})}>← Change space</button></div></div>{art}</section>}
 {step===2&&<section className="mj-summary"><span className="mj-symbol" aria-hidden="true">残心</span><p className="mj-kicker">A little intention</p><h1 ref={heading} tabIndex={-1}>A moment,<br/>chosen by you.</h1><p className="mj-intro">A little space for intention. Let's find the fragrance to accompany yours.</p><div className="mj-choices"><div><small>Your space</small><strong>{space}</strong><button className="mj-text" onClick={()=>dispatch({type:'edit-space'})}>Edit space</button></div><div><small>Your moment</small><strong>{moment}</strong><button className="mj-text" onClick={()=>dispatch({type:'edit-moment'})}>Edit moment</button></div></div><button className="mj-primary" onClick={()=>dispatch({type:'reveal'})}>Reveal my fragrance →</button></section>}
 {step===3&&p&&<section className="mj-layout mj-result" style={{'--match':p.color}}><LabelPack product={p} priority/><div><p className="mj-kicker">Your fragrance to explore</p><h1 ref={heading} tabIndex={-1}>Meet {p.name}.</h1><p className="mj-descriptor">{p.descriptor}</p><p className="mj-intro">{p.story}</p><p className="mj-selection">Chosen for <strong>{space} / {moment}</strong>.</p><div className="mj-actions"><Link className="mj-primary" to={`/collection/${p.slug}`}>Explore {p.name} →</Link><button className="mj-text" onClick={()=>dispatch({type:'restart'})}>Choose another moment</button></div><p className="mj-note">{p.size} / Eau de Parfum</p></div></section>}
 </div><p className="mj-assurance">A fragrance to accompany your moment.</p></div>
}
