import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {asset} from '../data';
import {useStore} from '../context/StoreContext';
import {ButtonLink,FeatureGrid,ProductVisual} from '../components/UI';
export default function Home(){const {products}=useStore(),[slide,setSlide]=useState(0),[paused,setPaused]=useState(false),[deal,setDeal]=useState(false);const slides=[{name:'Zanshin',title:'Begin with<br><em>the moment.</em>',subtitle:'Fragrance chosen by feeling, not just by name. Four identities. Infinite moments.',scene:'scene-house.webp',label:'zanshin-logo-full.png'},...products.map(p=>({name:p.name,title:`Meet<br><em>${p.name}.</em>`,subtitle:`${p.descriptor} ${p.mood}`,scene:p.scene,label:p.label}))];useEffect(()=>{if(paused)return;const id=setInterval(()=>setSlide(v=>(v+1)%slides.length),6500);return()=>clearInterval(id)},[paused,slides.length]);return <>
<section className="hero" aria-label="Zanshin fragrance banners"><div className="hero-slides">{slides.map((s,i)=><article key={s.name} className={`hero-slide ${slide===i?'active':''}`} aria-hidden={slide!==i}><div className="hero-bg" style={{backgroundImage:`url(${asset(s.scene)})`}}/><div className="hero-copy"><span className="eyebrow">{i?'The collection':'The house of Zanshin'} / 0{i+1}</span><h1 dangerouslySetInnerHTML={{__html:s.title}}/><p>{s.subtitle}</p><div className="hero-links"><ButtonLink to="/collection">Explore collection</ButtonLink><ButtonLink light to="/find-your-moment">Find your moment</ButtonLink></div></div><div className="hero-bottle-zone" aria-hidden="true"><div className="bottle-shadow"/><div className="hero-bottle"><img src={asset('concept-bottle.webp')} alt=""/><img className={`hero-bottle-label ${i===0?'house-label':''}`} src={asset(s.label)} alt=""/><div className="hero-bottle-shine"/></div></div><span className="hero-meta">{s.name} / 0{i+1} of 05 · Concept bottle</span></article>)}</div><div className="hero-ui"><div className="hero-controls"><button className="hero-arrow" onClick={()=>setSlide((slide+4)%5)} aria-label="Previous slide">←</button><div className="hero-dots">{slides.map((s,i)=><button key={s.name} className={`hero-dot ${slide===i?'active':''}`} onClick={()=>setSlide(i)} aria-label={`Show ${s.name}`}/>)}</div><button className="hero-arrow" onClick={()=>setSlide((slide+1)%5)} aria-label="Next slide">→</button></div><button className="motion-button" onClick={()=>setPaused(v=>!v)}>{paused?'Play motion':'Pause motion'}</button></div></section>
<section className="story"><div className="story-visual"><img src={asset('about-presence.webp')} alt="Sculptural brush circle in a stone landscape"/><div className="story-visual-mark">A presence that stays.</div></div><div className="story-copy"><span className="eyebrow">01 / The idea behind Zanshin</span><img className="story-logo-lockup" src={asset('zanshin-logo-full.png')} alt="Zanshin — Begin with the Moment"/><p className="story-intro">A presence that stays<br/><em>with the moment.</em></p><p>Zanshin takes its name from a Japanese idea of lasting presence. Give the moment your attention—and carry its feeling beyond the moment itself.</p><Link className="outline-link" to="/our-story">Read our story <span>↗</span></Link></div></section>
<section className="home-paths container"><div><span className="eyebrow">Begin with the moment</span><h2>Who do you want to be<br/><em>in this moment?</em></h2><p>Choose by purpose, mood or occasion. The quiz leads to a fragrance recommendation and your bag.</p><ButtonLink to="/find-your-moment">Start the quiz</ButtonLink></div><div><span className="eyebrow">Explore Zanshin</span><h2>Four identities.<br/><em>One invitation.</em></h2><p>Discover the feeling behind every fragrance, then visit its own page.</p><Link className="outline-link" to="/collection">Explore the collection <span>↗</span></Link></div></section>
<section className="moment-finder home-finder-teaser"><div className="container finder-heading"><span className="eyebrow">A more personal way to choose</span><h2>Find your <em>moment.</em></h2><p>A day, a place, a person. Start with what matters now.</p></div><div className="moment-cards">{products.map(p=><Link className="moment-card" to="/find-your-moment" key={p.slug}><img src={asset(p.lifestyle)} alt={`${p.name} moment`}/><span className="card-content"><small>{p.moments[0]}</small><strong>{p.name}</strong><span className="card-arrow">↗</span></span></Link>)}</div></section>
<section className="collection-intro"><div className="container intro-grid"><div><span className="eyebrow">The collection / four identities</span><h2>Four ways to<br/><em>meet the moment.</em></h2></div><p>From focused mornings to magnetic evenings, each fragrance has its own energy.</p></div><div className="collection-nav">{products.map((p,i)=><Link to={`/collection/${p.slug}`} key={p.slug}><small>0{i+1} / {p.descriptor.split('.')[0]}</small><strong>{p.name} ↗</strong></Link>)}</div></section>
{products.map((p,i)=><section className={`product ${i%2?'reverse':''}`} key={p.slug} style={{'--accent':p.color}}><div className="product-main"><ProductVisual product={p} index={i}/><div className="product-copy"><span className="eyebrow">0{i+1} / A moment to feel</span><h2>{p.name}</h2><div className="product-tagline">{p.descriptor}</div><p>{p.story}</p><div className="moment-examples"><strong>Moments like</strong><span>{p.moments.join(' · ')}</span></div><Link className="outline-link" to={`/collection/${p.slug}`}>Explore {p.name} <span>↗</span></Link></div></div></section>)}
<section className="home-commerce"><div className="container"><div className="client-section-head"><span className="eyebrow">Collection / discovery / gifting</span><h2>Make it yours.</h2><p>Explore four full size fragrance identities, or preview future discovery and gifting ideas.</p></div><FeatureGrid items={[{kicker:'Catalogue',title:'The four fragrances',text:'Each identity has a dedicated page connected to the shopping bag.',to:'/collection',link:'Explore catalogue'},{kicker:'Discovery',title:'Find more than one',text:'A discovery set concept. Final contents and price await approval.',to:'/discovery-gifting',link:'Preview discovery'},{kicker:'Gifting',title:'For someone else',text:'A gifting path ready for approved product details.',to:'/discovery-gifting',link:'Preview gifting'}]}/><button className="deal-tab" onClick={()=>setDeal(true)}>Deal of the day ↗</button></div></section>
{deal&&<><div className="deal-shade" onClick={()=>setDeal(false)}/><aside className="deal-drawer open"><button className="close-button" onClick={()=>setDeal(false)}>×</button><span className="eyebrow">Deal of the day / preview</span><h2>Today’s spotlight.</h2><p>Offer details are awaiting approval. No unconfirmed discount is shown.</p><img src={asset('scene-house.webp')} alt="Zanshin collection"/><ButtonLink to="/collection">Explore Zanshin</ButtonLink></aside></>}
<section className="packaging home-packaging"><div className="container packaging-layout"><div className="packaging-copy"><span className="eyebrow">The considered details</span><h2>More than<br/><em>a first impression.</em></h2><p>Explore the Connected carton from every side.</p><Link className="outline-link" to="/packaging">See full box design <span>↗</span></Link></div><div className="packaging-art"><div className="package-image-shell"><img src={asset('connected-carton-full.webp')} alt="Connected carton flat artwork"/></div></div></div></section>
<section className="home-editorial"><div className="container editorial-grid">{[['/community','Influencer / loyalty / community','The people around the moment.','Explore creator and community spaces.'],['/how-to-buy','Awareness / education','Know the path from moment to bag.','See how quiz, products and bag connect.'],['/engage','Game / engagement','Let the moment surprise you.','Try the interactive moment shuffle.']].map(x=><Link to={x[0]} key={x[0]}><span className="eyebrow">{x[1]}</span><h2>{x[2]}</h2><p>{x[3]}</p><strong>Explore ↗</strong></Link>)}</div></section>
<section className="home-testimonials"><div className="container"><span className="eyebrow">Testimonials / sample preview</span><h2>Words that <em>stay.</em></h2><p>Approved customer feedback will replace these clearly labelled sample quotes.</p><div className="review-grid"><article className="review-card"><div className="review-quote">“</div><p>The moment-led way of choosing makes the collection feel personal.</p><span>Sample testimonial 01</span></article><article className="review-card"><div className="review-quote">“</div><p>Each identity has its own mood, making the collection easy to explore.</p><span>Sample testimonial 02</span></article></div></div></section>
</>}
