import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {asset,fallbackProducts} from '../data';
import LabelPack from '../components/LabelPack';
import '../enso-home.css';
const homeImage=name=>asset(`home-approved/${name}.webp`);
const fresh=name=>asset(`enso-home/${name}.png`);
const campaigns=[
 {title:<>Every <em>moment</em><br/>begins with you.</>,label:'Focused / A little clarity',tone:'#4d7f9c',art:'enso-focused.webp',duration:10000},
 {title:<>Step into<br/><em>possibility.</em></>,label:'Energised / Momentum',tone:'#344b89',art:'enso-energised.webp',duration:5000},
 {title:<>Closer to<br/><em>your people.</em></>,label:'Connected / Belonging',tone:'#58674c',art:'enso-connected.webp',duration:5000},
 {title:<>Presence,<br/><em>on your terms.</em></>,label:'Magnetized / Confidence',tone:'#8b3c4c',art:'enso-magnetized.webp',duration:5000}
];
function Enso({art,priority}){return <div className="zh-enso-art" aria-hidden="true"><img src={asset(`enso-home/${art}`)} alt="" fetchPriority={priority?"high":"auto"}/><div className="zh-water-ripple"/></div>}
const moments=[{photo:()=>fresh('focused-man'),alt:'A man concentrating at a sunlit desk'},{photo:()=>'/films/energised-original-poster.png',alt:'A woman welcoming a new day'},{photo:()=>homeImage('connected'),alt:'Friends sharing an unhurried conversation'},{photo:()=>fresh('shared-presence'),alt:'A woman and man arriving at a gallery together'}];
const circle=[{title:'A clearer morning',photo:'/films/focused-original-poster.png',film:'/films/focused-original-motion.mp4',to:'focused'},{title:'New energy',photo:'/films/energised-original-poster.png',film:'/films/energised-original-motion.mp4',to:'energised'},{title:'Your daily ritual',photo:homeImage('ritual'),to:'focused'},{title:'Time together',photo:homeImage('connected'),to:'connected'},{title:'Own your evening',photo:fresh('shared-presence'),to:'magnetized'},{title:'A moment for yourself',photo:homeImage('focused'),to:'focused'}];
function FilmDialog({film,onClose}){const dialog=useRef(null),video=useRef(null),[failed,setFailed]=useState(false);useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();return()=>previous?.focus()},[]);return <dialog ref={dialog} className="zh-film-dialog" onClose={onClose} onClick={e=>{if(e.target===e.currentTarget)dialog.current.close()}} aria-labelledby="film-title"><button className="zh-close" aria-label="Close film" onClick={()=>dialog.current.close()}>&times;</button><h2 id="film-title">{film.title}</h2>{failed?<p>Film unavailable. You can still <Link to={`/collection/${film.to}`} onClick={onClose}>explore this fragrance</Link>.</p>:<video ref={video} controls playsInline preload="metadata" poster={film.photo} onError={()=>setFailed(true)}><source src={film.film} type="video/mp4"/></video>}<p>Campaign film / <Link to={`/collection/${film.to}`} onClick={onClose}>Explore the fragrance &rarr;</Link></p></dialog>}
export default function Home(){const [active,setActive]=useState(0),[film,setFilm]=useState(null),[intention,setIntention]=useState(0),[reduced,setReduced]=useState(false),rail=useRef(null);useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(mq.matches);update();mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update)},[]);useEffect(()=>{if(reduced)return;const timer=setTimeout(()=>setActive(n=>(n+1)%campaigns.length),campaigns[active].duration);return()=>clearTimeout(timer)},[active,reduced]);function scroll(direction){rail.current.scrollBy({left:direction*rail.current.clientWidth*.75,behavior:reduced?'instant':'smooth'})}
return <div className="zanshin-home"><div className="zh-opening"><section className="zh-stage" aria-label="Zanshin campaign slideshow" aria-roledescription="carousel">{campaigns.map((c,i)=><div key={i} className={`zh-slide ink ${i===active?'active':''}`} style={{'--campaign-tone':c.tone}} aria-hidden={i!==active}><Enso art={c.art} priority={i===0}/><div className="zh-hero-copy"><span className="zh-kicker">{c.label}</span><h1>{c.title}</h1><Link tabIndex={i===active?0:-1} className="zh-pill" to="/find-your-moment">Find your moment <span aria-hidden="true">&rarr;</span></Link></div></div>)}<div className="zh-dots" aria-label="Select a campaign">{campaigns.map((c,i)=><button key={i} aria-label={`Show campaign ${i+1}: ${c.label}`} aria-pressed={active===i} onClick={()=>setActive(i)}><span className="slider-dot"/></button>)}</div></section><aside className="zh-arch"><h2>Four intentions.<br/>One presence.</h2><LabelPack product={fallbackProducts[0]} priority/><Link className="zh-pill" to="/collection">Explore Zanshin &rarr;</Link></aside></div><div className="zh-editorial">
<section className="ze-story" aria-labelledby="ze-story-title">
 <div className="ze-story-image"><img src={homeImage('ritual')} alt="A quiet fragrance ritual in natural light" loading="lazy"/><span>A little pause. A different kind of presence.</span></div>
 <div className="ze-story-copy"><span className="ze-eyebrow">01 / The Zanshin philosophy</span><h2 id="ze-story-title">Less noise.<br/>More <em>you.</em></h2><p className="ze-lead">Be here. Be yourself.</p><p>Not every day asks for the same version of you. Some call for clarity. Others, a little courage, a closer connection or the energy to begin again.</p><p>Zanshin is a small personal ritual for those moments. Choose an intention. Take a breath. Meet the day as yourself.</p><Link className="ze-text-link" to="/our-story">Inside our philosophy <span aria-hidden="true">↗</span></Link></div>
</section>
<section className="ze-collection" aria-labelledby="ze-collection-title">
 <header className="ze-section-head"><div><span className="ze-eyebrow">02 / A fragrance for your intention</span><h2 id="ze-collection-title">Many sides of you.<br/><em>One place to begin.</em></h2></div><p>You don't have to be one thing.<br/>Find the fragrance that meets you here.</p></header>
 <div className="ze-select" role="group" aria-label="Choose a fragrance to explore">{fallbackProducts.map((p,i)=><button key={p.slug} type="button" aria-pressed={intention===i} onClick={()=>setIntention(i)} style={{'--tone':p.color}}><span>0{i+1}</span>{p.name}<span aria-hidden="true">↗</span></button>)}</div>
 {fallbackProducts.map((p,i)=><article key={p.slug} hidden={intention!==i} className="ze-fragrance" style={{'--tone':p.color}} aria-label={p.name}><div className="ze-fragrance-life"><img src={moments[i].photo()} alt={moments[i].alt} loading="lazy"/><span>{p.mood}</span></div><div className="ze-fragrance-details"><span className="ze-eyebrow">Eau de parfum / {p.size}</span><h3>{p.name}</h3><p>{p.story}</p><div className="ze-moments">{p.moments.map(m=><span key={m}>{m}</span>)}</div><Link className="ze-text-link" to={`/collection/${p.slug}`}>Discover {p.name} <span aria-hidden="true">↗</span></Link></div><div className="ze-fragrance-pack"><LabelPack product={p}/><span>{p.descriptor}</span></div></article>)}
 <div className="ze-collection-foot"><span>Four intentions. Yours to explore.</span><Link className="ze-text-link" to="/collection">Meet the whole collection ↗</Link></div>
</section>
<section className="ze-ritual" aria-labelledby="ze-ritual-title"><div className="ze-ritual-copy"><span className="ze-eyebrow">03 / Make it your own</span><h2 id="ze-ritual-title">A small ritual.<br/><em>A shift in the day.</em></h2><div className="ze-ritual-step"><span>01</span><div><h3>Pause for yourself.</h3><p>Leave a little space between what just happened and what comes next.</p></div></div><div className="ze-ritual-step"><span>02</span><div><h3>Choose how you want to feel.</h3><p>Clear, energised, connected or confident. Let your intention lead.</p></div></div><div className="ze-ritual-step"><span>03</span><div><h3>Carry it into your moment.</h3><p>A familiar fragrance. A deep breath. A day that feels a little more like you.</p></div></div><Link className="ze-text-link" to="/how-to-buy">Explore the ritual ↗</Link></div><div className="ze-ritual-image"><img src={fresh('shared-presence')} alt="A woman and man sharing an evening at a gallery" loading="lazy"/><span>Presence is personal.</span></div></section>
<section className="zh-circle"><header><div><h2>Join the Zanshin Circle.</h2><p>Different people. Shared moments.</p></div><div className="zh-arrows"><button onClick={()=>scroll(-1)} aria-label="Previous moments">&larr;</button><button onClick={()=>scroll(1)} aria-label="Next moments">&rarr;</button></div></header><div className="zh-rail" ref={rail} tabIndex={0} aria-label="Zanshin campaign moments">{circle.map(c=><article key={c.title}>{c.film?<button className="zh-media" aria-label={`Watch ${c.title}`} onClick={()=>setFilm(c)}><img src={c.photo} alt={c.title} loading="lazy"/><span className="zh-play" aria-hidden="true">&#9654;</span></button>:<Link className="zh-media" to={`/collection/${c.to}`}><img src={c.photo} alt={c.title} loading="lazy"/></Link>}<span className="zh-caption">{c.title}</span></article>)}</div><p className="zh-note">Zanshin campaign imagery &amp; films</p><Link className="zh-link" to="/community">Discover our community &rarr;</Link></section><section className="ze-finder"><img src={asset('zanshin-logo-full.png')} alt="" aria-hidden="true"/><span className="ze-eyebrow">Your next moment starts here</span><h2>How do you want<br/>to <em>feel today?</em></h2><p>Start with where you're going. Discover what feels like you.</p><Link className="zh-pill" to="/find-your-moment">Find your moment <span aria-hidden="true">↗</span></Link><span className="ze-finder-note">Your space. Your intention. Your fragrance.</span></section></div>{film&&<FilmDialog film={film} onClose={()=>setFilm(null)}/>}</div>}
