import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useStore} from '../context/StoreContext';
import {money,asset} from '../data';
import {SaveFragrance} from './ShopUtilities';
import LabelPack from '../components/LabelPack';
import '../fragrance-detail.css';
const feelings={focused:{title:'A quieter, brighter you.',copy:'An open notebook. A fresh perspective. Time for the work that matters to you. Focused is an invitation to be present with one thing at a time.'},energised:{title:'Momentum lives in the present.',copy:'For new beginnings, open horizons and the quiet excitement of stepping into the day. Energised accompanies the moments you choose to move forward.'},connected:{title:'Closer to what matters.',copy:'Belonging lives in shared laughter, open conversations and the ease of being together. Connected is for the people, places and moments that make life feel like yours.'},magnetized:{title:'Presence, on your terms.',copy:'A moment to yourself before you leave. An invitation worth accepting. Magnetized celebrates the confidence of arriving comfortably and completely as yourself.'}};
export default function Product(){
 const {slug}=useParams(),{products,add}=useStore(),[qty,setQty]=useState(1),[message,setMessage]=useState('');
 useEffect(()=>{setQty(1);setMessage('')},[slug]);
 const p=products.find(x=>x.slug===slug);
 if(!p)return <section className="utility-page"><h1>Fragrance not found.</h1><Link to="/collection">Explore the collection</Link></section>;
 const feeling=feelings[p.slug];
 return <div className="fragrance-detail" style={{'--fragrance':p.color}}>
 <section className="fd-opening"><div className="fd-gallery"><LabelPack product={p} priority/><p>Bottle & carton presentation concept</p></div><div className="fd-copy"><nav className="fd-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/collection">Fragrances</Link><span>/</span><span aria-current="page">{p.name}</span></nav><span className="fd-kicker">A moment for what matters</span><h1>{p.name}</h1><p className="fd-descriptor">{p.descriptor}</p><p className="fd-size">{p.size} / Eau de Parfum</p><p className="fd-price">{money(p.price)}<small>Sample price</small></p><div className="fd-purchase"><div className="fd-quantity"><button aria-label="Decrease quantity" disabled={qty<=1} onClick={()=>setQty(q=>q-1)}>−</button><output aria-label="Quantity">{qty}</output><button aria-label="Increase quantity" disabled={qty>=20} onClick={()=>setQty(q=>q+1)}>+</button></div><button className="fd-button" onClick={()=>{add(p.slug,qty);setMessage(`${qty} ${p.name} added to your bag.`)}}>Add to bag <span aria-hidden="true">→</span></button><SaveFragrance slug={p.slug} name={p.name}/></div><p className="fd-status" role="status">{message}</p><p className="fd-intro">{p.story}</p><div className="fd-signatures"><span>50 ml<br/><small>Eau de Parfum</small></span><span>Your intention<br/><small>Your moment</small></span><span>Zanshin<br/><small>Begin with the moment</small></span></div></div></section>
 <nav className="fd-section-nav" aria-label="Fragrance information">{[['feeling','The feeling'],['moments','Your moments'],['ritual','The ritual'],['details','Details']].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
 <section id="feeling" className="fd-feeling"><img src={asset(`home-approved/${p.slug}.webp`)} alt={`${p.name}: ${p.mood}`} loading="lazy"/><div><span className="fd-kicker">The feeling</span><h2>{feeling.title}</h2><p>{feeling.copy}</p><span className="fd-mantra">Begin with the moment</span></div></section>
 <section className="fd-information"><article id="moments"><span className="fd-index">01</span><h2>Your moments</h2><p>{p.mood}</p><ul>{p.moments.map(m=><li key={m}>{m}</li>)}</ul><Link className="fd-link" to="/find-your-moment">Find your moment →</Link></article><article id="ritual"><span className="fd-index">02</span><h2>The ritual</h2><p>Pause. Choose your intention. Apply to pulse points and allow your fragrance to settle.</p><p className="fd-small">Avoid eyes and irritated skin. Enjoy fragrance in your own way.</p><Link className="fd-link" to="/how-to-buy">Your fragrance guide →</Link></article><article id="details"><span className="fd-index">03</span><h2>The details</h2><dl><div><dt>Format</dt><dd>Eau de Parfum</dd></div><div><dt>Size</dt><dd>{p.size}</dd></div><div><dt>Identity</dt><dd>{p.name}</dd></div></dl><details><summary>Packaging & purchase information</summary><p>The bottle and carton are presentation concepts using the supplied labels. Prices are samples. Demo orders do not include live payment or shipping.</p><Link className="fd-link" to="/contact">Ask us about {p.name} →</Link></details></article></section>
 <section className="fd-related"><div className="fd-related-heading"><div><span className="fd-kicker">Explore Zanshin</span><h2>More moments. A deeper you.</h2></div><Link className="fd-link" to="/collection">View all fragrances →</Link></div><div className="fd-related-grid">{products.filter(x=>x.slug!==slug).map(x=><Link to={`/collection/${x.slug}`} key={x.slug} style={{'--fragrance':x.color}}><div className="fd-related-art"><LabelPack product={x} bottleOnly/></div><h3>{x.name} <span aria-hidden="true">→</span></h3><p>{x.descriptor}</p></Link>)}</div></section>
 </div>
}
