import {useState} from 'react';
import {Link} from 'react-router-dom';
import {asset,fallbackProducts} from '../data';
import {useStore} from '../context/StoreContext';
import LabelPack from './LabelPack';
import './HomeChapters.css';

export function EnsoEffect(){const [pulse,setPulse]=useState(0);return <div className="hc-enso"><span className="za-eyebrow">Why Zanshin</span><button className="hc-enso-touch" onClick={()=>setPulse(n=>n+1)} aria-label="Replay the Enso effect"><span key={pulse} className="hc-rings" aria-hidden="true"/><img src={asset('enso-home/enso-focused.webp')} alt="An open ink Enso circle above gentle water ripples"/></button><h3>The Enso effect.</h3><p>A pause to return to yourself.<br/>An intention to carry into your day.</p><span className="hc-caption">Touch the circle. Begin again.</span><Link className="za-link" to="/our-story">Discover our philosophy &#8599;</Link></div>}
const moods=[['focused','Keep your head in the game.','Clarity for the task in front of you.','enso-home/focused-man.png'],['connected','The vibe is better together.','Make time for your people.','home-approved/connected.webp'],['magnetized','Certified rizz.','Show up as your most confident self.','enso-home/shared-presence.png'],['energised','Sweat is the new flex.','A little momentum for your next move.','home-approved/energised.webp']];
export function MomentInvitation(){return <section className="hc-moments" aria-labelledby="hc-moments-title"><header className="za-heading"><div><span className="za-eyebrow">Find your moment</span><h2 id="hc-moments-title">What are you stepping into?</h2><p>Choose an intention to explore, or let the quiz guide you.</p></div><Link className="zh-pill" to="/find-your-moment">Take the quiz &#8599;</Link></header><div className="hc-polaroids">{moods.map(([slug,title,copy,img],i)=>{const product=fallbackProducts.find(p=>p.slug===slug);return <Link key={slug} className="hc-flip-card" to={`/collection/${slug}`} aria-label={`Explore ${product.name} fragrance details`} style={{'--tilt':`${[-3,2,-2,3][i]}deg`,'--tone':product.color}}><div className="hc-flip-inner"><div className="hc-flip-front"><img src={asset(img)} alt="" loading="lazy"/><div><span className="za-eyebrow">{product.name}</span><h3>{title}</h3><p>{copy}</p><span className="hc-explore">Explore this intention &#8599;</span></div></div><div className="hc-flip-back" aria-hidden="true"><span className="za-eyebrow">Begin with the moment</span><LabelPack product={product} bottleOnly/><h3>{product.name}</h3><p>{product.descriptor}</p><span className="hc-flip-cta">Discover the fragrance &#8599;</span></div></div></Link>})}</div><ol className="hc-journey"><li><span>01</span>Choose your space</li><li><span>02</span>Find your moment</li><li><span>03</span>Meet your fragrance</li></ol></section>}
export function QualityPromise(){return <section className="hq-details" aria-labelledby="hc-quality-title"><div className="hq-intro"><span className="za-eyebrow">The details matter</span><h2 id="hc-quality-title">Our approach.<br/><em>Considered, every day.</em></h2><p>A fragrance you connect with. A presentation you make your own.</p><Link className="za-link" to="/packaging">Explore the presentation &#8599;</Link></div><div className="hq-facts">{[['01','Eau de parfum','A personal finishing touch to your everyday ritual.'],['02','50 ml','Your chosen intention, in a bottle for your daily routine.'],['03','Bottle & carton','A matching presentation in each fragrance’s signature colour.'],['04','Find your fit','Explore each intention, or let our moment quiz guide you.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>}
const giftIntentions = [
 {slug:'connected',label:'Just because',message:'Life feels warmer with you in it.',note:'For the conversations that run late, the everyday laughter, and all the little moments that become ours.',sign:'Here’s to more time together.'},
 {slug:'focused',label:'A new chapter',message:'For everything you’re becoming.',note:'For your first day, your next big idea, and the quiet determination that makes you, you.',sign:'I’m cheering for you.'},
 {slug:'energised',label:'A little lift',message:'Here’s to your next adventure.',note:'For fresh starts, spontaneous plans, and the spark you bring into every room.',sign:'Keep following that feeling.'},
 {slug:'magnetized',label:'Their moment',message:'The world is yours tonight.',note:'For the moments worth dressing up for, and the confidence to show up exactly as you are.',sign:'Go make it memorable.'}
];
export function BuildYourBag(){
 const {add}=useStore();
 const [choice,setChoice]=useState(0),[added,setAdded]=useState(false);
 const intention=giftIntentions[choice];
 const product=fallbackProducts.find(p=>p.slug===intention.slug);
 function select(index){setChoice(index);setAdded(false)}
 function submit(){if(added)return;add(product.slug);setAdded(true)}
 return <section className="gift-letter" aria-labelledby="hc-bag-title" style={{'--gift-ink':product.color}}>
  <header className="gift-heading"><span className="za-eyebrow">The art of giving · Zanshin</span><h2 id="hc-bag-title">Some feelings<br/>deserve <em>a fragrance.</em></h2><p>A thank you. A fresh start. A simple “I thought of you”.<br/>Begin with what you want to say.</p></header>
  <div className="gift-reasons" role="group" aria-label="What would you like your gift to say?">{giftIntentions.map((item,index)=><button key={item.slug} type="button" aria-pressed={choice===index} onClick={()=>select(index)}><span aria-hidden="true">0{index+1}</span>{item.label}</button>)}</div>
  <div className="gift-table" key={product.slug}>
   <div className="gift-correspondence"><span className="gift-small-label">A thought to give</span><article className="gift-paper"><span className="gift-to">To someone special,</span><h3>{intention.message}</h3><p>{intention.note}</p><span className="gift-sign">{intention.sign}</span><span className="gift-seal" aria-hidden="true">Z</span></article><span className="gift-note-caption">A little inspiration for your own message.</span></div>
   <div className="gift-object"><span className="gift-halo" aria-hidden="true"/><span className="gift-ribbon" aria-hidden="true"/><div className="gift-object-pack"><LabelPack product={product}/></div><span className="gift-object-caption">An intention to unwrap.<br/>A feeling to carry.</span></div>
  </div>
  <footer className="gift-footer"><div className="gift-match"><span className="za-eyebrow">Your gifting edit</span><h3>{product.name}</h3><p>50 ml Eau de parfum · Matching presentation carton</p></div><div className="gift-purchase"><Link className="za-link" to={`/collection/${product.slug}`}>Meet {product.name} &#8599;</Link><button type="button" className="zh-pill" onClick={submit} disabled={added}>{added?'Added to your bag':'Give this feeling'} <span aria-hidden="true">&#8599;</span></button><span role="status">{added?<Link to="/bag">Review your bag &#8594;</Link>:'Choose with intention. Give with love.'}</span></div></footer>
 </section>
}
// Replace demo entries with approved, permission-cleared creator and customer media.
// Campaign films are deliberately identified as samples, never customer endorsements.
export function Testimonials({onFilm}){return <section className="hv-stories" aria-labelledby="hc-voices-title"><header className="za-heading"><div><span className="za-eyebrow">The people behind the moments</span><h2 id="hc-voices-title">Fragrance, in real life.</h2></div><p>Small rituals. Personal perspectives.</p></header><div className="hv-creator-heading"><h3>Creator stories</h3><span>Sample campaign films</span></div><div className="hv-films">{[['A quieter kind of morning.','A moment to pause before the day begins.','focused'],['A fresh start, on your terms.','A little energy for wherever the day takes you.','energised']].map(([title,copy,slug],i)=><button key={slug} onClick={()=>onFilm({title,photo:`/films/${slug}-original-poster.png`,film:`/films/${slug}-original-motion.mp4`,to:slug})}><div className="hv-film-image"><img src={`/films/${slug}-original-poster.png`} alt="" loading="lazy"/><span className="hv-play" aria-hidden="true">&#9654;</span></div><div className="hv-film-copy"><span className="za-eyebrow">Film 0{i+1} / {slug}</span><h3>{title}</h3><p>{copy}</p><span className="hv-watch">Watch the film <span aria-hidden="true">&#8599;</span></span></div></button>)}</div><div className="hv-customers"><header><div><span className="za-eyebrow">Customer moments</span><h3>The little things<br/><em>that stay with you.</em></h3></div><p>Illustrative sample testimonials.<br/>Verified customer stories will take their place.</p></header><div className="hv-quotes">{[['Focused','A moment for myself.','Before the day gets busy, I like to take a minute that is just mine.'],['Connected','Back to being present.','My favourite part of the evening is leaving work behind and catching up with my people.'],['Magnetized','Feeling like myself.','Getting ready is a ritual. Choosing my fragrance is the finishing touch.']].map(([name,title,quote],i)=><figure key={name} style={{'--quote-tone':['#456883','#505b37','#6b2d39'][i]}}><span className="hv-quote-mark" aria-hidden="true">&#8220;</span><h4>{title}</h4><blockquote>{quote}</blockquote><figcaption><span>{name}</span><small>Sample testimonial</small></figcaption></figure>)}</div></div></section>}
